# -*- coding: utf-8 -*-

from django.forms import Form, ChoiceField

NUMBER_CHOICES \
    = (('', ''),
       (1, '1'),
       (2, '2'),
       (3, '3'),
       (4, '4'),
       (5, '5'),
       (6, '6'),
       (7, '7'),
       (8, '8'),
       (9, '9'))


class Form1(Form):
    n0 = ChoiceField(choices=NUMBER_CHOICES, initial='', required=False)
    n1 = ChoiceField(choices=NUMBER_CHOICES, initial='', required=False)
    n2 = ChoiceField(choices=NUMBER_CHOICES, initial='', required=False)
    n3 = ChoiceField(choices=NUMBER_CHOICES, initial='', required=False)
    n4 = ChoiceField(choices=NUMBER_CHOICES, initial='', required=False)
    n5 = ChoiceField(choices=NUMBER_CHOICES, initial='', required=False)
    n6 = ChoiceField(choices=NUMBER_CHOICES, initial='', required=False)
    n7 = ChoiceField(choices=NUMBER_CHOICES, initial='', required=False)
    n8 = ChoiceField(choices=NUMBER_CHOICES, initial='', required=False)
    n9 = ChoiceField(choices=NUMBER_CHOICES, initial='', required=False)
    n10 = ChoiceField(choices=NUMBER_CHOICES, initial='', required=False)
    n11 = ChoiceField(choices=NUMBER_CHOICES, initial='', required=False)
    n12 = ChoiceField(choices=NUMBER_CHOICES, initial='', required=False)
    n13 = ChoiceField(choices=NUMBER_CHOICES, initial='', required=False)
    n14 = ChoiceField(choices=NUMBER_CHOICES, initial='', required=False)
    n15 = ChoiceField(choices=NUMBER_CHOICES, initial='', required=False)
    n16 = ChoiceField(choices=NUMBER_CHOICES, initial='', required=False)
    n17 = ChoiceField(choices=NUMBER_CHOICES, initial='', required=False)
    n18 = ChoiceField(choices=NUMBER_CHOICES, initial='', required=False)
    n19 = ChoiceField(choices=NUMBER_CHOICES, initial='', required=False)
    n20 = ChoiceField(choices=NUMBER_CHOICES, initial='', required=False)
    n21 = ChoiceField(choices=NUMBER_CHOICES, initial='', required=False)
    n22 = ChoiceField(choices=NUMBER_CHOICES, initial='', required=False)
    n23 = ChoiceField(choices=NUMBER_CHOICES, initial='', required=False)
    n24 = ChoiceField(choices=NUMBER_CHOICES, initial='', required=False)
    n25 = ChoiceField(choices=NUMBER_CHOICES, initial='', required=False)
    n26 = ChoiceField(choices=NUMBER_CHOICES, initial='', required=False)
    n27 = ChoiceField(choices=NUMBER_CHOICES, initial='', required=False)
    n28 = ChoiceField(choices=NUMBER_CHOICES, initial='', required=False)
    n29 = ChoiceField(choices=NUMBER_CHOICES, initial='', required=False)
    n30 = ChoiceField(choices=NUMBER_CHOICES, initial='', required=False)
    n31 = ChoiceField(choices=NUMBER_CHOICES, initial='', required=False)
    n32 = ChoiceField(choices=NUMBER_CHOICES, initial='', required=False)
    n33 = ChoiceField(choices=NUMBER_CHOICES, initial='', required=False)
    n34 = ChoiceField(choices=NUMBER_CHOICES, initial='', required=False)
    n35 = ChoiceField(choices=NUMBER_CHOICES, initial='', required=False)
    n36 = ChoiceField(choices=NUMBER_CHOICES, initial='', required=False)
    n37 = ChoiceField(choices=NUMBER_CHOICES, initial='', required=False)
    n38 = ChoiceField(choices=NUMBER_CHOICES, initial='', required=False)
    n39 = ChoiceField(choices=NUMBER_CHOICES, initial='', required=False)
    n40 = ChoiceField(choices=NUMBER_CHOICES, initial='', required=False)
    n41 = ChoiceField(choices=NUMBER_CHOICES, initial='', required=False)
    n42 = ChoiceField(choices=NUMBER_CHOICES, initial='', required=False)
    n43 = ChoiceField(choices=NUMBER_CHOICES, initial='', required=False)
    n44 = ChoiceField(choices=NUMBER_CHOICES, initial='', required=False)
    n45 = ChoiceField(choices=NUMBER_CHOICES, initial='', required=False)
    n46 = ChoiceField(choices=NUMBER_CHOICES, initial='', required=False)
    n47 = ChoiceField(choices=NUMBER_CHOICES, initial='', required=False)
    n48 = ChoiceField(choices=NUMBER_CHOICES, initial='', required=False)
    n49 = ChoiceField(choices=NUMBER_CHOICES, initial='', required=False)
    n50 = ChoiceField(choices=NUMBER_CHOICES, initial='', required=False)
    n51 = ChoiceField(choices=NUMBER_CHOICES, initial='', required=False)
    n52 = ChoiceField(choices=NUMBER_CHOICES, initial='', required=False)
    n53 = ChoiceField(choices=NUMBER_CHOICES, initial='', required=False)
    n54 = ChoiceField(choices=NUMBER_CHOICES, initial='', required=False)
    n55 = ChoiceField(choices=NUMBER_CHOICES, initial='', required=False)
    n56 = ChoiceField(choices=NUMBER_CHOICES, initial='', required=False)
    n57 = ChoiceField(choices=NUMBER_CHOICES, initial='', required=False)
    n58 = ChoiceField(choices=NUMBER_CHOICES, initial='', required=False)
    n59 = ChoiceField(choices=NUMBER_CHOICES, initial='', required=False)
    n60 = ChoiceField(choices=NUMBER_CHOICES, initial='', required=False)
    n61 = ChoiceField(choices=NUMBER_CHOICES, initial='', required=False)
    n62 = ChoiceField(choices=NUMBER_CHOICES, initial='', required=False)
    n63 = ChoiceField(choices=NUMBER_CHOICES, initial='', required=False)
    n64 = ChoiceField(choices=NUMBER_CHOICES, initial='', required=False)
    n65 = ChoiceField(choices=NUMBER_CHOICES, initial='', required=False)
    n66 = ChoiceField(choices=NUMBER_CHOICES, initial='', required=False)
    n67 = ChoiceField(choices=NUMBER_CHOICES, initial='', required=False)
    n68 = ChoiceField(choices=NUMBER_CHOICES, initial='', required=False)
    n69 = ChoiceField(choices=NUMBER_CHOICES, initial='', required=False)
    n70 = ChoiceField(choices=NUMBER_CHOICES, initial='', required=False)
    n71 = ChoiceField(choices=NUMBER_CHOICES, initial='', required=False)
    n72 = ChoiceField(choices=NUMBER_CHOICES, initial='', required=False)
    n73 = ChoiceField(choices=NUMBER_CHOICES, initial='', required=False)
    n74 = ChoiceField(choices=NUMBER_CHOICES, initial='', required=False)
    n75 = ChoiceField(choices=NUMBER_CHOICES, initial='', required=False)
    n76 = ChoiceField(choices=NUMBER_CHOICES, initial='', required=False)
    n77 = ChoiceField(choices=NUMBER_CHOICES, initial='', required=False)
    n78 = ChoiceField(choices=NUMBER_CHOICES, initial='', required=False)
    n79 = ChoiceField(choices=NUMBER_CHOICES, initial='', required=False)
    n80 = ChoiceField(choices=NUMBER_CHOICES, initial='', required=False)
