# coding: utf-8

from django.forms import ChoiceField, Form
CHOICES = (
	('', ''),
    (1, '1'),
    (2, '2'),
    (3, '3'),
    (4, '4'),
    (5, '5'),
    (6, '6'),
    (7, '7'),
    (8, '8'),
    (9, '9'),
)

class Form1(Form):
    A1 = ChoiceField(choices=CHOICES, initial='', required=False)
    A2 = ChoiceField(choices=CHOICES, initial='', required=False)
    A3 = ChoiceField(choices=CHOICES, initial='', required=False)
    A4 = ChoiceField(choices=CHOICES, initial='', required=False)
    A5 = ChoiceField(choices=CHOICES, initial='', required=False)
    A6 = ChoiceField(choices=CHOICES, initial='', required=False)
    A7 = ChoiceField(choices=CHOICES, initial='', required=False)
    A8 = ChoiceField(choices=CHOICES, initial='', required=False)
    A9 = ChoiceField(choices=CHOICES, initial='', required=False)
    B1 = ChoiceField(choices=CHOICES, initial='', required=False)
    B2 = ChoiceField(choices=CHOICES, initial='', required=False)
    B3 = ChoiceField(choices=CHOICES, initial='', required=False)
    B4 = ChoiceField(choices=CHOICES, initial='', required=False)
    B5 = ChoiceField(choices=CHOICES, initial='', required=False)
    B6 = ChoiceField(choices=CHOICES, initial='', required=False)
    B7 = ChoiceField(choices=CHOICES, initial='', required=False)
    B8 = ChoiceField(choices=CHOICES, initial='', required=False)
    B9 = ChoiceField(choices=CHOICES, initial='', required=False)
    C1 = ChoiceField(choices=CHOICES, initial='', required=False)
    C2 = ChoiceField(choices=CHOICES, initial='', required=False)
    C3 = ChoiceField(choices=CHOICES, initial='', required=False)
    C4 = ChoiceField(choices=CHOICES, initial='', required=False)
    C5 = ChoiceField(choices=CHOICES, initial='', required=False)
    C6 = ChoiceField(choices=CHOICES, initial='', required=False)
    C7 = ChoiceField(choices=CHOICES, initial='', required=False)
    C8 = ChoiceField(choices=CHOICES, initial='', required=False)
    C9 = ChoiceField(choices=CHOICES, initial='', required=False)
    D1 = ChoiceField(choices=CHOICES, initial='', required=False)
    D2 = ChoiceField(choices=CHOICES, initial='', required=False)
    D3 = ChoiceField(choices=CHOICES, initial='', required=False)
    D4 = ChoiceField(choices=CHOICES, initial='', required=False)
    D5 = ChoiceField(choices=CHOICES, initial='', required=False)
    D6 = ChoiceField(choices=CHOICES, initial='', required=False)
    D7 = ChoiceField(choices=CHOICES, initial='', required=False)
    D8 = ChoiceField(choices=CHOICES, initial='', required=False)
    D9 = ChoiceField(choices=CHOICES, initial='', required=False)
    E1 = ChoiceField(choices=CHOICES, initial='', required=False)
    E2 = ChoiceField(choices=CHOICES, initial='', required=False)
    E3 = ChoiceField(choices=CHOICES, initial='', required=False)
    E4 = ChoiceField(choices=CHOICES, initial='', required=False)
    E5 = ChoiceField(choices=CHOICES, initial='', required=False)
    E6 = ChoiceField(choices=CHOICES, initial='', required=False)
    E7 = ChoiceField(choices=CHOICES, initial='', required=False)
    E8 = ChoiceField(choices=CHOICES, initial='', required=False)
    E9 = ChoiceField(choices=CHOICES, initial='', required=False)
    F1 = ChoiceField(choices=CHOICES, initial='', required=False)
    F2 = ChoiceField(choices=CHOICES, initial='', required=False)
    F3 = ChoiceField(choices=CHOICES, initial='', required=False)
    F4 = ChoiceField(choices=CHOICES, initial='', required=False)
    F5 = ChoiceField(choices=CHOICES, initial='', required=False)
    F6 = ChoiceField(choices=CHOICES, initial='', required=False)
    F7 = ChoiceField(choices=CHOICES, initial='', required=False)
    F8 = ChoiceField(choices=CHOICES, initial='', required=False)
    F9 = ChoiceField(choices=CHOICES, initial='', required=False)
    G1 = ChoiceField(choices=CHOICES, initial='', required=False)
    G2 = ChoiceField(choices=CHOICES, initial='', required=False)
    G3 = ChoiceField(choices=CHOICES, initial='', required=False)
    G4 = ChoiceField(choices=CHOICES, initial='', required=False)
    G5 = ChoiceField(choices=CHOICES, initial='', required=False)
    G6 = ChoiceField(choices=CHOICES, initial='', required=False)
    G7 = ChoiceField(choices=CHOICES, initial='', required=False)
    G8 = ChoiceField(choices=CHOICES, initial='', required=False)
    G9 = ChoiceField(choices=CHOICES, initial='', required=False)
    H1 = ChoiceField(choices=CHOICES, initial='', required=False)
    H2 = ChoiceField(choices=CHOICES, initial='', required=False)
    H3 = ChoiceField(choices=CHOICES, initial='', required=False)
    H4 = ChoiceField(choices=CHOICES, initial='', required=False)
    H5 = ChoiceField(choices=CHOICES, initial='', required=False)
    H6 = ChoiceField(choices=CHOICES, initial='', required=False)
    H7 = ChoiceField(choices=CHOICES, initial='', required=False)
    H8 = ChoiceField(choices=CHOICES, initial='', required=False)
    H9 = ChoiceField(choices=CHOICES, initial='', required=False)
    I1 = ChoiceField(choices=CHOICES, initial='', required=False)
    I2 = ChoiceField(choices=CHOICES, initial='', required=False)
    I3 = ChoiceField(choices=CHOICES, initial='', required=False)
    I4 = ChoiceField(choices=CHOICES, initial='', required=False)
    I5 = ChoiceField(choices=CHOICES, initial='', required=False)
    I6 = ChoiceField(choices=CHOICES, initial='', required=False)
    I7 = ChoiceField(choices=CHOICES, initial='', required=False)
    I8 = ChoiceField(choices=CHOICES, initial='', required=False)
    I9 = ChoiceField(choices=CHOICES, initial='', required=False)

